CREATE TABLE [dbo].[SYNCTABLE]
(
[IdSincTable] [bigint] NOT NULL,
[SincTableName] [nvarchar] (max) COLLATE Modern_Spanish_CI_AS NULL,
[OrderTable] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[SYNCTABLE] ADD CONSTRAINT [PK__SYNCTABL__CCE9DD3200551192] PRIMARY KEY CLUSTERED  ([IdSincTable]) ON [PRIMARY]
GO
