CREATE TABLE [dbo].[MODIFIEDDATA]
(
[IdModifiedData] [bigint] NOT NULL,
[IdSincTable] [bigint] NULL,
[IsModified] [bit] NULL,
[ServerModifiedDate] [bigint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MODIFIEDDATA] ADD CONSTRAINT [PK__MODIFIED__C8DC73943B75D760] PRIMARY KEY CLUSTERED  ([IdModifiedData]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MODIFIEDDATA] ADD CONSTRAINT [FK__MODIFIEDD__IdSin__70DDC3D8] FOREIGN KEY ([IdSincTable]) REFERENCES [dbo].[SYNCTABLE] ([IdSincTable])
GO
