CREATE TABLE [dbo].[GET_EXPEDIENTE]
(
[IdExpediente] [bigint] NOT NULL,
[IsActive] [bit] NOT NULL,
[LastModifiedDate] [bigint] NOT NULL,
[IsModified] [bit] NOT NULL,
[IdAsunto] [bigint] NULL,
[ServerLastModifiedDate] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GET_EXPEDIENTE] ADD CONSTRAINT [GET_EXPEDIENTE_PK] PRIMARY KEY CLUSTERED  ([IdExpediente]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GET_EXPEDIENTE] ADD CONSTRAINT [GET_ASUNTO_GET_EXPEDIENTE_FK1] FOREIGN KEY ([IdAsunto]) REFERENCES [dbo].[GET_ASUNTO] ([IdAsunto])
GO
