CREATE TABLE [dbo].[REL_DESTINATARIO_CCP]
(
[IdDestinatarioCcp] [bigint] NOT NULL,
[IdRol] [bigint] NOT NULL,
[IdAsunto] [bigint] NOT NULL,
[IsActive] [bit] NOT NULL,
[LastModifiedDate] [bigint] NOT NULL,
[IsModified] [bit] NOT NULL,
[ServerLastModifiedDate] [bigint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REL_DESTINATARIO_CCP] ADD CONSTRAINT [REL_DESTINATARIO_CCP_PK] PRIMARY KEY CLUSTERED  ([IdDestinatarioCcp]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REL_DESTINATARIO_CCP] ADD CONSTRAINT [FK_REL_DESTINATARIO_CCP_GET_ASUNTO] FOREIGN KEY ([IdAsunto]) REFERENCES [dbo].[GET_ASUNTO] ([IdAsunto])
GO
ALTER TABLE [dbo].[REL_DESTINATARIO_CCP] ADD CONSTRAINT [FK_REL_DESTINATARIO_CCP_APP_ROL] FOREIGN KEY ([IdRol]) REFERENCES [dbo].[APP_ROL] ([IdRol])
GO
