CREATE TABLE [dbo].[APP_USUARIO_ROL]
(
[IdUsuarioRol] [bigint] NOT NULL,
[IdUsuario] [bigint] NOT NULL,
[IdRol] [bigint] NOT NULL,
[IsActive] [bit] NOT NULL,
[LastModifiedDate] [bigint] NOT NULL,
[IsModified] [bit] NOT NULL,
[ServerLastModifiedDate] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[APP_USUARIO_ROL] ADD CONSTRAINT [APP_USUARIO_ROL_PK] PRIMARY KEY CLUSTERED  ([IdUsuarioRol]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[APP_USUARIO_ROL] ADD CONSTRAINT [APP_ROL_APP_USUARIO_ROL_FK1] FOREIGN KEY ([IdRol]) REFERENCES [dbo].[APP_ROL] ([IdRol])
GO
ALTER TABLE [dbo].[APP_USUARIO_ROL] ADD CONSTRAINT [APP_USUARIO_APP_USUARIO_ROL_FK1] FOREIGN KEY ([IdUsuario]) REFERENCES [dbo].[APP_USUARIO] ([IdUsuario])
GO
