CREATE TABLE [dbo].[REL_SIGNATARIO_EXTERNO]
(
[IdAsunto] [bigint] NOT NULL,
[IdDeterminante] [bigint] NOT NULL,
[IdSignatarioExterno] [bigint] NOT NULL,
[Fecha] [datetime] NULL,
[IsActive] [bit] NOT NULL,
[IsModified] [bit] NOT NULL,
[LastModifiedDate] [bigint] NOT NULL,
[ServerLastModifiedDate] [bigint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REL_SIGNATARIO_EXTERNO] ADD CONSTRAINT [REL_SIGNATARIO_EXTERNO_PK] PRIMARY KEY CLUSTERED  ([IdSignatarioExterno]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REL_SIGNATARIO_EXTERNO] ADD CONSTRAINT [GET_ASUNTO_REL_SIGNATARIO_EXTERNO_FK1] FOREIGN KEY ([IdAsunto]) REFERENCES [dbo].[GET_ASUNTO] ([IdAsunto])
GO
ALTER TABLE [dbo].[REL_SIGNATARIO_EXTERNO] ADD CONSTRAINT [CAT_DETERMINANTE_REL_SIGNATARIO_EXTERNO_FK1] FOREIGN KEY ([IdDeterminante]) REFERENCES [dbo].[CAT_DETERMINANTE] ([IdDeterminante])
GO
